### ISSUE TITLE
Implement inactivity timeout 

### ISSUE THREAD

**Issue by mattkm** [team-sudoers/atm#1]
- The program should have an “inactivity timeout” for logged in users.  When the inactivity period expires, the program will automatically display a warning message. If the user does not select the option to continue or chooses to log out, the system will log off and return to the login page.

- Prompt that will remind you that you are about to timeout. Should ask if you want to continue or exit.

- 30 seconds of inactivity will trigger the “inactivity timeout” function.

**Comment by rdent3** [comment]
Inactivity timeout implemented during weekly meeting.
