### ISSUE TITLE
Support native currencies for each language

### ISSUE THREAD

**Issue by mattkm** [team-sudoers/atm#5]
Received from: Jacob Heddings

Hello Sudoers,

Excellent work! Everything looks very thorough, and the ATM design seems to work well. I have a small piece of feedback/suggestion: maybe for each language, there could be a small section that displays the totals in that language's native currency. For example, for France:

CHECKING

$100.00 (€89.58)

Probably not a necessity but it's something to consider.

Great design work!

Jacob

**Comment by rdent3** [comment]
This feature will not be added due to this ATM being based in the U.S., thus it is out of scope for this project.
